More orderly bootstrap scripts.

diff --git a/bin/california/deploy b/bin/california/deploy
--- a/bin/california/deploy
+++ b/bin/california/deploy
@@ -9,23 +9,48 @@ function gateway() {
 function sshdo() {
     local machine=$1
     shift
-    gateway /usr/bin/ssh -A $machine.california.runpup.net $@
+    gateway /usr/bin/ssh -A $machine.california.runpup.net $@ > /dev/null
+    return $?
 }
 
 function pull() {
     local machine=$1
-    /usr/bin/ssh -A alvar.user.south.california.runpup.com \
-        /usr/bin/ssh -A $machine.california.runpup.net \
-        "\"(cd $JANITOR && /usr/bin/git pull)\""
+    /usr/bin/ssh -A $machine.california.runpup.net bash -c "\"(cd $JANITOR && /usr/bin/git pull)\""
 }
 
-/usr/bin/sudo /usr/sbin/unbound-control -c /etc/unbound/unbound.conf flush_zone .
-gateway bash -c "'(cd $JANITOR && /usr/bin/git pull)'"
-gateway $JANITOR/var/bin/dns/private/bootstrap
-gateway /usr/bin/sudo /usr/sbin/unbound-control -c /etc/unbound/unbound.conf flush_zone .
-pull alvar.data.north
-sshdo alvar.data.north /usr/bin/sudo /usr/bin/yum update -y
-sshdo alvar.data.north $JANITOR/var/bin/dns/private/bootstrap
+function step() {
+    local message=$1
+    shift
+    echo -n "$message"
+    $@
+    if [ $? -eq 0 ]
+    then
+        echo " [OK]"
+    else
+        echo " [FAILED]"
+        exit 1
+    fi
+}
+
+function flush_zone() {
+    /usr/bin/sudo /usr/sbin/unbound-control -c /etc/unbound/unbound.conf flush_zone . > /dev/null
+}
+
+function get_pull() {
+    /bin/bash -c "'(cd $JANITOR && /usr/bin/git pull > /dev/null)'"
+}
+
+dir=$(/bin/readlink -f "$(/usr/bin/dirname $0)/../..")
+california=$dir/bin/california
+
+step "Flush unbound on $(/bin/hostname): " $california/flush_zone
+step "Update Puppy from git on $(/bin/hostname): " $california/git_pull
+step "Boostrap private DNS on $(/bin/hostname): " $JANITOR/var/bin/dns/private/bootstrap
+step "Boostrap private DNS on alvar.data.north: " $california/git_pull_there alvar.data.north
+step "yum update of alvar.data.south: " sshdo alvar.data.south /usr/bin/sudo /usr/bin/yum update -y
+step "Boostrap private DNS on alvar.data.south: " $california/git_pull_there alvar.data.north
+step "yum update of alvar.data.north: " sshdo alvar.data.north /usr/bin/sudo /usr/bin/yum update -y
+step "Bootstrap private DNS on alvar.data.north" sshdo alvar.data.north $JANITOR/var/bin/dns/private/bootstrap
 pull alvar.data.south
 sshdo alvar.data.north /usr/bin/sudo /usr/bin/yum update -y
 sshdo alvar.data.south $JANITOR/var/bin/dns/private/bootstrap
@@ -35,4 +60,4 @@ sshdo alvar.balance.north /usr/bin/sudo /usr/bin/yum update -y
 pull alvar.balance.north
 sshdo alvar.user.north /usr/bin/sudo /usr/bin/yum update -y
 pull alvar.user.north
-sshdo alvar.balance.north $JANITOR/var/bin/pg/wal/mount
+sshdo alvar.balance.north /usr/bin/sudo $JANITOR/var/bin/pg/wal/mount
