Rotate no longer schedules self.
Split rotate up into the steps. It no longer schedules itself.

diff --git a/bin/dns/public/rotate b/bin/dns/public/rotate
--- a/bin/dns/public/rotate
+++ b/bin/dns/public/rotate
@@ -1,17 +1,32 @@
 #!/bin/bash
 
-if [ -z "$1" ]; then
-    echo "usage: $0 domain" 1>&2
+ksk=0
+while getopts ":d::s:k" opt; do
+    case $opt in
+        d)
+            domain=$OPTARG
+            ;;
+        s)
+            step=$OPTARG
+            ;;
+        k)
+            ksk=1
+            ;;
+        \?)
+            echo "Invalid option: -$OPTARG" >&2
+            ;;
+    esac
+done
+
+if [ -z "$domain" -o -z "$step" ]; then
+    echo "usage $0 -k -d <domain> -s <step>" 1>&2
     exit 1
 fi
-domain=$1
+
 zonedir=/mnt/dns/var/$domain
 zonefile=$zonedir/$domain.zone
 
 BIG_DOWNLOAD=http://mirror.facebook.net/centos/6.2/isos/i386/CentOS-6.2-i386-bin-DVD1.iso
-
-zoneday=3
-keyinterval=2
 
 # This reminder is sent when zone keys are ready to rotate, with detailed
 # intructions for forgetful old system adminsitrators like myself.
@@ -76,39 +91,43 @@ function generate_zsk()
     wait $curl_pid 2> /dev/null
 }
 
-# In order for all that below to work correctly, we need to publish keys as
-# well as generate them. Ideally, key publishing would be triggered when keys
-# are updated here. I'll have to develop confidence that this works correclty
+# In order for all that below to work correctly, we need to publish keys as well
+# as generate them. Ideally, key publishing would be triggered when keys are
+# updated here. I'll have to develop confidence that this works correclty
 # attended, before I'm willing to trust it unattended. (But, at this point it is
 # failing because it is ignored and the keys are expiring outright.)
+case $step in
+    # Happy zone day! Time to generate some new zone files. If we are at our key
+    # signing key rotation interval, then we'll rotate keys as well.
+    create)
+        /bin/mkdir -p $zonedir/incoming
+        touch "$zonedir/incoming/$(/bin/date '+timestamp-%Y-%m-%d')"
+        [ 1 -eq $ksk ] && generate_ksk
+        generate_zsk
+        ;;
 
-# Happy zone day! Time to generate some new zone files. If we are at our key
-# signing key rotation interval, then we'll rotate keys as well.
-if [ $(/bin/date '+%w') -eq $zoneday ]; then
-    /bin/mkdir -p $zonedir/incoming
-    touch "$zonedir/incoming/$(/bin/date '+timestamp-%Y-%m-%d')"
-    [ $(( $(/bin/date '+%U') % $keyinterval )) -eq 0 ] && generate_ksk
-    generate_zsk
+    # Zone say plus one. We move directories around. In order for this to work
+    # correctly, we need to publish keys
+    promote)
+        if [ -e $zonedir/incoming ]; then
+            incoming=$(date -d '-1 day' '+timestamp-%Y-%m-%d') 
+            if [ ! -e $zonedir/incoming/$incoming ]; then
+                echo "Incoming keys not as expected." 1>&2
+                exit 1
+            fi
+            /bin/mv $zonedir/current    $zonedir/outgoing
+            /bin/mv $zonedir/incoming   $zonedir/current
+        fi
+        ;;
 
-# Zone say plus one. We move directories around. In order for this to work
-# correctly, we need to publish keys
-elif [ $(/bin/date '+%w') -eq $(( ( $zoneday + 1 ) % 7 )) ]; then
-    if [ -e $zonedir/incoming ]; then
-        incoming=$(date -d '-1 day' '+timestamp-%Y-%m-%d') 
-        if [ ! -e $zonedir/incoming/$incoming ]; then
-            echo "Incoming keys not as expected." 1>&2
-            exit 1
+    purge)
+        if [ -e $zonedir/outgoing ]; then
+            timestamp=$(/bin/ls $zonedir/outgoing/timestamp-* | sed 's/.*\/timestamp-//')
+            mkdir -p $zonedir/history
+            /bin/mv $zonedir/outgoing    $zonedir/history/$timestamp
+            if [ $(( $(/bin/date -d '-2 days' '+%U') % $keyinterval )) -eq 0 ]; then 
+                ksk_delete_message
+            fi
         fi
-        /bin/mv $zonedir/current    $zonedir/outgoing
-        /bin/mv $zonedir/incoming   $zonedir/current
-    fi
-elif [ $(/bin/date '+%w') -eq $(( ( $zoneday + 2 ) % 7 )) ]; then
-    if [ -e $zonedir/outgoing ]; then
-        timestamp=$(/bin/ls $zonedir/outgoing/timestamp-* | sed 's/.*\/timestamp-//')
-        mkdir -p $zonedir/history
-        /bin/mv $zonedir/outgoing    $zonedir/history/$timestamp
-        if [ $(( $(/bin/date -d '-2 days' '+%U') % $keyinterval )) -eq 0 ]; then 
-            ksk_delete_message
-        fi
-    fi
-fi
+        ;;
+esac
